remote_theme: "alshedivat/al-folio"

title: Matteo Parma - 2261454
url: "https://teoparma.github.io"
baseurl: ""
repository: "teoparma/teoparma.github.io"

author: Teo Parma
email: parmamatteo02@gmail.com
github_username: teoparma
timezone: Europe/Rome

navigation:
  - {name: 'Home', link: '/'}
  - {name: 'Homeworks', link: '/homeworks/'}

enable_contact: true
enable_blog: true
enable_research: true
enable_projects: true

collections:
  news:
    output: true
    permalink: /news/:path/

include:
  - .htaccess

exclude:
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
